// <auto-generated />
using System;
using Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryDBContext))]
    partial class RepositoryDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ProcessEngine.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastActivated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activated");

                    b.Property<DateTime?>("LastCompiled")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_compiled");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("version");

                    b.Property<string>("VersionBuild")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("version_build");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_application_name");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.DatabaseActionModule", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.HasKey("ModuleId");

                    b.ToTable("database_action_modules", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.FieldModule", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer")
                        .HasColumnName("field_type");

                    b.HasKey("ModuleId");

                    b.ToTable("field_modules", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ModuleType")
                        .HasColumnType("integer")
                        .HasColumnName("module_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("idx_modules_application");

                    b.HasIndex("ModuleType")
                        .HasDatabaseName("idx_modules_type");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_modules_name");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.ProcessModule", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<bool>("DynamicCall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("dynamic_call");

                    b.Property<bool>("Remote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("remote");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subtype");

                    b.HasKey("ModuleId");

                    b.ToTable("process_modules", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.ProcessModuleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<int?>("ActionModuleType")
                        .HasColumnType("integer")
                        .HasColumnName("action_module_type");

                    b.Property<int?>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<bool>("CommentedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("commented_flag");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FailLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fail_label");

                    b.Property<string>("LabelName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label_name");

                    b.Property<string>("PassLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pass_label");

                    b.Property<Guid>("ProcessModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_module_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("ProcessModuleId")
                        .HasDatabaseName("idx_process_details_module");

                    b.HasIndex("ProcessModuleId", "LabelName")
                        .IsUnique()
                        .HasDatabaseName("uq_process_label");

                    b.HasIndex("ProcessModuleId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("uq_process_sequence");

                    b.ToTable("process_module_details", (string)null);
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.DatabaseActionModule", b =>
                {
                    b.HasOne("Domain.ProcessEngine.Entities.Module", "Module")
                        .WithOne()
                        .HasForeignKey("Domain.ProcessEngine.Entities.DatabaseActionModule", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.FieldModule", b =>
                {
                    b.HasOne("Domain.ProcessEngine.Entities.Module", "Module")
                        .WithOne()
                        .HasForeignKey("Domain.ProcessEngine.Entities.FieldModule", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.Module", b =>
                {
                    b.HasOne("Domain.ProcessEngine.Entities.Application", "Application")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.ProcessModule", b =>
                {
                    b.HasOne("Domain.ProcessEngine.Entities.Module", "Module")
                        .WithOne()
                        .HasForeignKey("Domain.ProcessEngine.Entities.ProcessModule", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.ProcessModuleDetail", b =>
                {
                    b.HasOne("Domain.ProcessEngine.Entities.ProcessModule", "ProcessModule")
                        .WithMany("Details")
                        .HasForeignKey("ProcessModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessModule");
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.Application", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Domain.ProcessEngine.Entities.ProcessModule", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
